require 'chunky_png'
require 'pry'
require 'matrix'

require_relative 'acts_as_raytracer/position'
require_relative 'acts_as_raytracer/world'
require_relative 'acts_as_raytracer/film'
require_relative 'acts_as_raytracer/camera'
require_relative 'acts_as_raytracer/ray'
require_relative 'acts_as_raytracer/raster'
require_relative 'acts_as_raytracer/pixel'
require_relative 'acts_as_raytracer/sphere'
require_relative 'acts_as_raytracer/light_source'
require_relative 'acts_as_raytracer/colour'
